In [2]:
[1, 2, 3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
[1,2,3] * [2,3,4]

TypeError: can't multiply sequence by non-int of type 'list'

# Numpy (Numerical Python)

In [11]:
import numpy as np

In [7]:
a= numpy.array([1,2,3])
a

array([1, 2, 3])

In [8]:
a*3

array([3, 6, 9])

# Math functions

In [12]:
numpy.sum(a)

6

In [13]:
np.sum(a)

6

In [14]:
np.mean(a)

2.0

# Random Number

In [19]:
np.random.rand(3,3)

array([[0.15399874, 0.59034705, 0.76039553],
       [0.1222604 , 0.77396067, 0.30401256],
       [0.1461369 , 0.50007404, 0.24696686]])

## mengontrol randomness

In [25]:
state = np.random.RandomState(42)
state.rand(3, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])